### PR TITLE
New implementation for computeCartesianPath()

### PR DESCRIPTION
**Pull request by rhaschke**
The Cartesian interpolator uses a JumpThreshold parameter to detect and reject a switch between IK solution branches leading to larger joint-space jumps. However, this approach is rather fragile: It is difficult to find a suitable threshold parameter and the approach requires a long-enough trajectory to work (at least 10 waypoints).
Particularly if the last requirement is not met, joint-space jumps can still occur unnoticed leading to a dangerous execution of an unchecked, large-volume trajectory.

This PR proposes a fundamentally different way to check for joint-space jumps, which works robustly and locally for any two adjacent waypoints: If the two waypoints are distant in joint-space, their half-way interpolation state will typically lead to a very strong deviation from the straight-line Cartesian path between them. This PR measures this deviation and rejects a trajectory if it exceeds a "precision" threshold.
Actually, the approach (recursively) introduces more waypoints in between to improve the precision of the linear Cartesian path. Thus, the method doesn't need to be provided with a good estimate of the `MaxEEFStep` parameter, it adjusts the step size dynamically to meet the given precision requirement. (This statement only holds if IK succeeds at all. In order to evaluate IK on a fine-grained grid and detect obstacles, one still needs the `MaxEEFStep` parameter.)

The following plots illustrate the new behavior. They all use the extremely coarse `MaxEEFStep` > 1m, resulting in a single initial step and then adjust the precision to introduce additional waypoints:
| 1 step, 0.3m precision | 1 step, collision not detected! |
|---|---|
| 1 step | collision |

| 1 + 1 steps, 0.1m precision | 1 + 3 steps, 0.025m precision |
|---|---|
| 2 steps | 4 steps |

I kept but deprecated the old JumpThreshold-based methods. I'm not sure how to best migrate the MoveGroup interface. To expose the new interface, we would need to introduce the `CartesianPrecision` argument as a message.
For now, I just dropped the JumpThreshold argument and resort to the default precision, which is 1mm. Given a reasonable `MaxEEFStep`, this should perfectly resolve the jump issues. I think, fiddling with the new parameter shouldn't be necessary in most cases.

### CODE REVIEW

**Comment by rhaschke** [comment]
FYI, @LeroyR

**Comment by captain-yoshi** [comment]
Very Nice! Always wanted to benchmark against Pilz :)

I tested on my setup, and it now works reliably with short trajectories. But for larger distance (see photos below), I often get `min_fraction` Achieved = 0.0. The same goals works with Pilz.

Here is my config (manually set in MTC cartesian_path.cpp). Using a version of Track-IK which is deterministic.
```
// image 1
moveit::core::CartesianPrecision precision;
precision.translational = 0.001;
precision.rotational = 0.01;
precision.max_resolution = 1e-5;

moveit::core::MaxEEFStep max(0, 0.0349066);

// image 2
moveit::core::CartesianPrecision precision;
precision.translational = 0.01;
precision.rotational = 0.01;
precision.max_resolution = 1e-5;

moveit::core::MaxEEFStep max(0, 0.0349066);

```

Do you have any insight on why this could happen ? I would assume that the min_fraction would be greater then 0 for these cases.

image

image

**Comment by rhaschke** [comment]
I suggest using a non-zero `MaxEEFStep(0.1, 0.035)`. Trying to jump to the target with a single IK call, might lead to unavoidable jumps. Did you use zero translational step in the past?

**Comment by captain-yoshi** [comment]
Wow this is a game changer :)

With the proposed config, this PR passes my huge Task which consist of + 1000 stages and generates 5200 waypoints ! Some limited benchmark (5 runs each).

| Solver                     | Time (s) | Waypoints |
|----------------------------|----------|-----------|
| Pilz                       | 3.6      | 6641      |
| CartesianPath (2 degree)   | 1.42     | 5197      |
| CartesianPath (0.5 degree) | 2.92     | 5197      |

> Did you use zero translational step in the past?

Never used in the past as it failed for short trajectories.

**Comment by rhaschke** [comment]
> Wow this is a game changer

I'm curious: where do you see a dramatic change? I was just expecting some more robustness when generating linear Cartesian trajectories. Particularly, I wasn't expecting faster computation.

**Comment by captain-yoshi** [comment]
Robustness is the key + same configuration for a wide variety of poses. Like I said, the solver went from a no go (from my perspective and project needs) to a potential alternative to Pilz.

It seems faster, but would have to change my configuration to match Pilz. Gotta check if it passes through the same planning plugins also.

**Comment by sea-bass** [comment]
> > Wow this is a game changer
> 
> I'm curious: where do you see a dramatic change? I was just expecting some more robustness when generating linear Cartesian trajectories. Particularly, I wasn't expecting faster computation.

If you have successive points where a joint interpolation is sufficient (and within tolerance), you can avoid having to solve IK at that point. So I can totally see the speedups that way!

**Review by sea-bass — COMMENTED** [review]
My same comments on https://github.com/moveit/moveit2/pull/2916 hold here.

**Review by sea-bass — APPROVED** [review]

**Comment by topguns837** [comment]
I have observed some weird bot motion after the changes in this P.R. I have opened an issue here : https://github.com/moveit/moveit/issues/3657

**Comment by InigoMoreno** [comment]
I don't understand why any changes have been made to the API so close to the noetic EOL.

**Comment by rhaschke** [comment]
> I don't understand why any changes have been made to the API so close to the noetic EOL.

Reaching EOL doesn't mean stopping development. ROS1 is to be continued: https://github.com/ros-o/ros-o

**Comment by InigoMoreno** [comment]
Yes, but the binaries are going to be frozen, and there are probably packages that use moveit that will not have time to update its binaries before that.

**Pull request merged**
