### PR TITLE
use acm for external collision

### PR DESCRIPTION
**Pull request by torydebra**
### Description

Check Issue #3639 

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/moveit/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://moveit.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/moveit/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by rhaschke — APPROVED** [review]
Looks good to me. @AndyZe, please comment.

**Comment by torydebra** [comment]
Sorry I see now that the acm was not updated, but it was fixed, so it is necessary to update it in the run to consider objects added after moveit_servo started

**Review by v4hn — APPROVED** [review]
makes sense and seems to be a clear oversight.

**Review by v4hn — CHANGES_REQUESTED** [review]
> Sorry I see now that the acm was not updated, but it was fixed, so it is necessary to update it in the run to consider objects added after moveit_servo started

I just spent some time looking at this as well. The main question is why the `CollisionCheck` class would copy the ACM in the first place instead of looking up the member from the planning scene.
I would suggest to scope both collision checks and get the locked planning scene within the scope once - instead of acquiring the lock twice as is currently the state.
Then you can also drop `acm_` as a member altogether and simple get a fresh reference within the locked scope each iteration.

**Comment by AndyZe** [comment]
I'd be happy to approve the PR as-is but @v4hn 's suggestion is prob a good idea. @v4hn is suggesting something like this, I think?

```
{
  planning_scene_montior::LockedPlanningSceneRO ls(planning_scene_monitor);
  collision_detection::AllowedCollisionMatrix acm = ls->getAllowedCollisionMatrix();
  // Do a timer-safe distance-based collision detection
  collision_result_.clear();
  ls->getCollisionEnv()->checkRobotCollision(...);
  ...
  ls->getCollisionEnvUnpadded()->checkSelfCollision(...);
}
```

**Comment by AndyZe** [comment]
> The main question is why the CollisionCheck class would copy the ACM in the first place instead of looking up the member from the planning scene.

Good point.

**Pull request closed without merging**
